# Generated by Django 6.0.6 on 2026-07-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='meetme_app.celebrity'),
        ),
    ]
