# Generated by Django 6.0.6 on 2026-07-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme_app', '0002_alter_package_celebrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
