# Generated by Django 6.0.6 on 2026-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme_app', '0003_package_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
