# Generated by Django 6.0.6 on 2026-07-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme_app', '0004_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
