# Generated by Django 6.0.6 on 2026-07-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme_app', '0005_alter_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_link', models.CharField(max_length=500)),
                ('support_text', models.CharField(default='Support', max_length=100)),
            ],
        ),
    ]
